### ISSUE TITLE
Exception - ACSPARAMS (OneLogin IDP)

### ISSUE THREAD

**Issue by chris-moberly** [CatalystIT-AU/moodle-auth_saml2#11]
Hello, thank you very much for sharing this awesome plugin with the community!

I apologize in advance for what might be a very simple user-error situation - I am the Moodle training administrator but not a developer, so am quite possibly overlooking something obvious.

I am using OneLogin as an IDP and have installed your SAML2 plugin into my Moodle 3.1 environment. OneLogin created an app based on the SP metadata file and all seems to flow properly.

URL for public XML file at OneLogin: https://app.onelogin.com/saml/metadata/560319

Errors generated in debug logs on my Moodle server:
```
[Tue Jul 05 13:25:08 2016] [error] [client 49.177.179.211] simpleSAMLphp WARNING [0398cc6049] Unable to find the SAML 2 binding used for this request.array (\n), referer: https://scality.onelogin.com/client/apps/
[Tue Jul 05 13:25:08 2016] [error] [client 49.177.179.211] simpleSAMLphp WARNING [0398cc6049] Request method: 'GET'array (\n), referer: https://scality.onelogin.com/client/apps/
```

Thank you for your hard work on this plugin!!!

**Comment by brendanheywood** [comment]
hi @chris-moberly,

Well in theory you shouldn't need to be a dev to get this to work :)

I'm not sure what is going on, the metadata looks pretty straight forward and simple, and it seems that onelogin is just passing back an empty request. I probably can't debug it much more without being able to reproduce it locally, against a onelogin idp. If you like you could get some paid support from us and we can look into it and fix this bug if it on the SP side, or perhaps you can try the onelogin specific auth plugin for moodle: https://moodle.org/plugins/auth_onelogin_saml

**Comment by chris-moberly** [comment]
@brendanheywood 
Thank you very much for the reply!

Unfortunately, OneLogin has not updated their plugin for Moodle 3 and does not seem interested in doing so. Let me figure out the priority of this for my group and I may come back with a request for paid support.

Have a great week and thanks again for your contribution!

**Comment by chris-moberly** [comment]
Hi Brendan,

I wonder if I could ask one more question before I go back to the drawing board on this.

I can see that I am getting 404 errors when my idp sends me back to the ACS URL. This "ACSPARAMS" seems to actually be a custom 404 page. I get this same 404 when just trying to browse to the URL manually.

When I look at my SP metadata file, I see a URL that doesn't exist. It looks like this:
`https://<my-site's-url>/auth/saml2/sp/saml2-acs.php/<my-site's-url>`

The URL does exist up to the last forward-slash, but then it is appending my site's name to the URL. That generates the 404. Browsing to the URL like this:
`https://<my-site's-url>/auth/saml2/sp/saml2-acs.php`
gets me the same 404 message.

Before I chase my tail too much more on this, could you let me know if the above is expected behavior or if there is something in my web server that I should be focusing on instead?

**Comment by brendanheywood** [comment]
Apache and php have a feature called slash params which uses PATH_INFO to make that last bit of the url work. Moodle itself also uses it for serving files so is usually already on by default and working but it can't hurt to test that. 

https://docs.moodle.org/31/en/Using_slash_arguments

The saml2-acs.php itself is only used for server to server posts, so I would not except it do anything useful in a browser unlike the metadata.php which should serve you an xml Doc in the browser. If the xml isn't working debug that first, then re-import the good xml into one login again

**Comment by chris-moberly** [comment]
Hi Brendan,

Thanks for taking the time to reply and also to explain this so clearly. This is much appreciated!

This makes perfect sense. PATH_INFO is indeed enabled, and the metadata xml does work properly. I think I may just need to shelf this part of the project for now.

Have a great day!

**Comment by brendanheywood** [comment]
It might be worth quickly testing your site against a public test idp just as http://www.testshib.org/ just to make sure there isn't anything wrong with your setup. If that works then we can narrow it down to a difference in the saml bindings or somethng particular to onelogin.

**Comment by chris-moberly** [comment]
Hi Brendan,

This was EXTREMELY helpful! Using the tool and the debug option in your plugin, I was able to determine that I was missing mcrypt for php. After installing mcrypt, I was able to successfully authenticate using testshib.

Happy times, thanks again - I just need to work with OneLogin to have them apply my new SP metadata XML and will update again here if this is working.

:)

**Comment by brendanheywood** [comment]
Ok great stuff, I've made a new issue #13 to warn loud and clear if mcrypt isn't installed and make that front and center. I'll close this one for now, feel free to reopen if there are other onelogin issues.

Thanks for the feedback :)

**Comment by dw085432-ship-it** [comment]
Absolutely
