### ISSUE TITLE
"Data Mapping" values not saving

### ISSUE THREAD

**Issue by datasmash** [CatalystIT-AU/moodle-auth_saml2#14]
Hello,

Once again, thank you for your hard work on this amazing plugin. This is all working great and authenticating existing users while creating new users in my Moodle environment.

One thing I have noticed is that when filling in the "Data Mapping" fields (I have specifically tried email address and first name) and then clicking "Save" that the values do not persist. The page refreshes with the values blank.

I do notice that there is mention of the mapping in your "To Do" area - is this feature still pending? If so, could you contact me regarding sponsoring the completion?

Again, thank you for posting this project and sharing with the world!!!

**Comment by chris-moberly** [comment]
Apologies, meant to log this with my business account. We are one in the same person. :)

Thanks!

**Comment by chris-moberly** [comment]
Just some more details.

Steps to reproduce:
1.) Start with functioning plugin
2.) Browse to Site Admin > Plugins > Authentication > SAML2
3.) Under "Data mapping" enter text into "First name" "Surname" or "Email address", Update local "on creation" and Lock value "Unlocked"
4.) Click "Save"
5.) See that page has refreshed and the text box for the field that was entered is now blank

I've used two computers with Firefox and Safari. My site is all HTTPS.

With debugging enabled in Moodle and this plugin, I don't see anything happening in the ssl_error log. In the ssl_access log, I see the following when I click "Save":
```
<ip address removed> - - [13/Jul/2016:01:43:09 +0000] "POST /admin/auth_config.php HTTP/1.1" 200 165500
<ip address removed> - - [13/Jul/2016:01:43:13 +0000] "POST /lib/ajax/service.php?sesskey=yFaMs6PONS HTTP/1.1" 200 27
```

**Comment by brendanheywood** [comment]
That has regressed, I'll look into it.

**Comment by cristianomariacumer** [comment]
It seems that a 

return true;

is missing [here](https://github.com/CatalystIT-AU/moodle-auth_saml2/blob/fb25ed27fe45f23af343cdd1440bcb1bbbd1f61f/auth.php#L425)

**Comment by brendanheywood** [comment]
Thanks again
