### ISSUE TITLE
Configure Signing of Logout request

### ISSUE THREAD

**Issue by cristianomariacumer** [CatalystIT-AU/moodle-auth_saml2#16]
Hello,

our ADFS IdP service requires that the logout request are signed. Where can I configure this?

**Comment by cristianomariacumer** [comment]
Found

in  config/authsources.php 

just add 

'sign.logout' => true,

at the end of the configuration array

**Comment by brendanheywood** [comment]
hi @cristianomariacumer did you just change this locally? Can you please put together a pull request?

**Comment by cristianomariacumer** [comment]
Hullo @brendanheywood, done
