### ISSUE TITLE
User profile field locking is not respected

### ISSUE THREAD

**Issue by mattporritt** [CatalystIT-AU/moodle-auth_saml2#23]
When user profile fields are locked in the SAML2 auth configuration page, users are still able to edit the locked fields in their own profile. This is present in Moodle 2.9 (but looks like it would affect other versions)
Dirty test script:
* Install and configure SAML2 auth plugin
* Configure firstname to be locked in saml2 auth settings
* Configure a non admin user to have saml2 auth
* Login in as the saml2 user
* Edit user profile

Firstname field is still editable.
This looks to be an incarnation of this tracker issue: https://tracker.moodle.org/browse/MDL-36987. I have a patch in the works that I'll lodge as a pull request once it is tested

**Comment by brendanheywood** [comment]
Correct fix should just use the get_config('auth/saml2') and have an upgrade script to fix legacy config data
