### ISSUE TITLE
Make data mapping config section collapsible 

### ISSUE THREAD

**Issue by dmitriim** [CatalystIT-AU/moodle-auth_saml2#26]
It's too painful to scroll down to save settings :) Would be awesome to have Data mapping collapsible or move it to another page.

**Comment by brendanheywood** [comment]
This is core code, so if anything is done it should be in core so all auth plugins benefit.

Half the problem is that this old mapping method hasn't been ported to the new settings.php api:

https://tracker.moodle.org/browse/MDL-12689
