### ISSUE TITLE
In some cases getting Exception - Destination in response doesn't match the current URL.

### ISSUE THREAD

**Issue by dmitriim** [CatalystIT-AU/moodle-auth_saml2#28]
We had this before with drupal SAML plugin. And we could replicate it again with this one. 
After migrating staging to nginx getting

Exception - Destination in response doesn't match the current URL. Destination is "https://URL/auth/saml2/sp/saml2-acs.php/SPNAME", current URL is "https://URL:80/auth/saml2/sp/saml2-acs.php/SPNAME"

Fixed by adding following to config array:

'baseurlpath'       => $CFG->wwwroot . '/auth/saml2/sp/',

**Comment by brendanheywood** [comment]
Fixed in https://github.com/CatalystIT-AU/moodle-auth_saml2/pull/30
