### ISSUE TITLE
Dual login not working, redirects to sso login page

### ISSUE THREAD

**Issue by brendanheywood** [CatalystIT-AU/moodle-auth_saml2#3]
From Sunil via moodle plugin directory:

> Great product but have a little problem. I'm using MySQL with Moodle and the SAML2 works great but if I try to login http://www.mydomain.com/login/index.php?saml=off and type in the admin username and pw it redirect me back to my SSO login page. Can someone please help so I can also login manually by turning off SAML via the URL. If I set "Dual Login" to YES it work but I want all users to use the SSO login and only for Administrator to use the manual login.

**Comment by cybercorey** [comment]
I ran across this today in my testing, the login form post back to the page without the ?saml=off making it redirect.

**Comment by brendanheywood** [comment]
Fixed and closing
