### ISSUE TITLE
ADFS 2.1: Logout results in an error

### ISSUE THREAD

**Issue by jlyle29** [CatalystIT-AU/moodle-auth_saml2#33]
Using ADFS 2.1 as our Idp sign in is working however logout does results in an error page from the ADFS server and the following in the ADFS event log:

> An error occurred during processing of the SAML logout request. 

>  Additional Data 

>  Caller identity: https://[SP URL]/auth/saml2/sp/metadata.php 
Logout initiator identity: http://[ADFS URL]/adfs/services/trust 
Error message: MSIS1014: SAML LogoutRequest and LogoutResponse messages must be signed when using SAML HTTP Redirect or HTTP POST binding. 
Exception details:  
User Action 
Ensure that the single logout service is configured properly for this relying party trust or claims provider trust in the AD FS configuration database.

I believe that while ADFS requires the logout requests and responses to be signed simplesamlphps default redirect.sign default is not to sign. Not sure how to confirm this?
([https://simplesamlphp.org/docs/1.8/simplesamlphp-reference-idp-remote](url))

if this is the case is there a way I can configure this?

**Comment by brendanheywood** [comment]
Try adding 'redirect.sign' => true, into the config/authsources.php file, if that works please let me know and I'll make that permanent.

**Comment by jlyle29** [comment]
Thanks for coming back to me. This appears to has worked, however ADFS was logging the following and failing to log in until I changed the ADFS Relying Party Conf to use SHA-1:

> SAML request is not signed with expected signature algorithm. SAML request is signed with signature algorithm http://www.w3.org/2001/04/xmldsig-more#rsa-sha256 . Expected signature algorithm is http://www.w3.org/2000/09/xmldsig#rsa-sha1 
> 
> User Action: 
> Verify that signature algorithm for the partner is configured as expected.

I am conscious that SHA-1 is deprecated in favor of SHA-256 is there a way to update this? - I am not sure whether this is hard coded into the plugin or grabbed from my OS settings?

**Comment by jlyle29** [comment]
That seems to have done the trick thanks!

Not sure whether I am being over paranoid but it looks like the certificates are using SHA-1 also amd the meta data still seems to advertise SHA-1.

**Comment by brendanheywood** [comment]
Thanks! I've baked both of those settings into master
