### ISSUE TITLE
Users not auto creating despite successful test and login

### ISSUE THREAD

**Issue by jesmith2095** [CatalystIT-AU/moodle-auth_saml2#34]
Good Day,
I have successfully installed and configured the module and tested successfully using both Test using isPassive and Test isAuthenticated and login, but when I login using SAML2, I receive the following message: You have logged in succesfully but we could not find your 'uid' attribute to associate you to an account in Moodle. I have verified that create users is enabled in the config and that Prevent  Account Creation when authenticating is not check under manage authentication. 

I'm hoping it is just something that I have overlooked, but I cannot seem to find what it might be. 

I am running Moodle 3 on Ubuntu 14.04 and MySQL 5.5.50 if that has any impact.

Thanks in advance,
Jeff

**Comment by brendanheywood** [comment]
It is looking for a saml attibute called 'uid' to match up with the moodle username but it can't find it. Depending on your idp it could be called 'username' or 'email' or anything. If you turn on debugging you should see a dump of all the attributes that get returned, work backwards to find it's label and then stick that in this config field:

![image](https://cloud.githubusercontent.com/assets/187449/17296497/e93a82ac-5844-11e6-992a-bd8de16cf21d.png)

**Comment by brendanheywood** [comment]
@jesmith2095 I'm going to close this, if you have any more question please fire up a new issue :)
