### ISSUE TITLE
Two parameters to include in the configuration 

### ISSUE THREAD

**Issue by asabolansky** [CatalystIT-AU/moodle-auth_saml2#4]
Hi, 
we have the Moodle behind a reverse proxy and we have to modify de baseurlpath in the config in the file config.php in the folder config.

We add this:

'baseurlpath' => 'https://mydomain.com/auth/saml2/',

Maybe, you can include this parameter in  the Moodle config interface.

Thanks
Alejandro

**Comment by brendanheywood** [comment]
There is only one valid value this can take for the system to work - so I'll just wire it directly and it won't be configurable. We just came across this exact same issue while porting this plugin to drupal as well.

What was the second parameter you wanted?

**Comment by asabolansky** [comment]
In our infrastructure, we don't  exchange metadata xml with our IDP (Simplesamlphp). We only use the entityID as string. I configure this value in  the config/authsources.php

       'entityID' => 'sp_app',

Regards,
Alejandro

**Comment by brendanheywood** [comment]
That doesn't sound right, it simply can't work without knowing what the idp url is in some way.

I suspect you are trying to migrate from an existing setup where you have a SSPHP instance acting as an SP next to moodle and then a second SSPHP instance as the idp? Take a look inside the /metadata/ director in your sp and see if there is file, probably saml20-idp-remote.php which contains the mapping from 'sp_app' to the real idp url.

All of this config is SSPHP internals which you shouldn't really ever be exposed to with this plugin.

**Comment by asabolansky** [comment]
Thanks!

I could resolve it with the metadata xml exchange.
