### ISSUE TITLE
ADFS Endpoints not HTTPS

### ISSUE THREAD

**Issue by Apex-Oil** [CatalystIT-AU/moodle-auth_saml2#44]
Not sure if it is something unique on our setup, but it is just defaults all around, but when trying to get ADFS to import the metadata file it errors as the URL are HTTP:// and not HTTPS://.

I have SSL setup and working for moodle auth.

I see that it should pull from the wwwroot in the main moodle config.php file but to try and keep the site as fast as possible it would be nice to just have authentication happen over HTTPS and not the full site.

But I made the change in the main moodle config.php but the metadata file does not update.

Any thoughts?

Thanks.

**Comment by brendanheywood** [comment]
The SP / Moodle metadata is statically cached in a file, it may not have picked up the changes to the wwwroot. Try clicking the regen button, then view the sp xml again and see if it's good

**Comment by Apex-Oil** [comment]
Well could I DERP any harder?  Thanks.  Total missed that part.  On to the next with mapping.  Thanks.

**Comment by brendanheywood** [comment]
Yeah it's a bit of a gotcha, it used to be generated on the fly every time but this made it harder to detect real changes in the xml as it was always different. I detect changes in the saml config and purge the cache but not at the site config level. I'll have a think about whether this is possible to detect and auto purge, or if you can think of other ways to make this more explicit and warn then I'll open to suggestions.

Also as an aside, nothing to do with saml, I would very strongly recommend you use https for the whole stie and don't attempt to use it for just auth. This opens you up to session fixation attacks and worse. Moodle has a 'loginhttps' option for this but it's frankly awful and gives a false sense of security. In this day and age fast TLS is easy and shouldn't be used as a reason for poor security. It's being deprecated:

https://tracker.moodle.org/browse/MDL-42834

**Comment by Apex-Oil** [comment]
Thanks for the heads up.
