### ISSUE TITLE
Fallback to other authentication method (e.g. LDAP)

### ISSUE THREAD

**Issue by danowar2k** [CatalystIT-AU/moodle-auth_saml2#45]
Hello,

I don't know if it would be feasible, but it would be nice for some fallback method in case an IDP is somehow unreachable.
Perhaps allow LDAP authentication if SSO is unavailable.

*sigh* I think the problem might rather be Moodle itself, as it allows only one auth method per user.

**Comment by brendanheywood** [comment]
This is trivial and already supported. If you set up ldap auth, then also turn on saml2 but allow 'dual auth' and also 'any auth' the you can login via either method at the same time.

However generally your saml server is backed by ldap so in most setups with won't help, you are just better setting up high availability ldap + saml so you don't need this workaround.

**Comment by danowar2k** [comment]
Regardgin that, I think I posted the issue to the issue tracker of the wrong saml authentication plugin for Moodle.
Incidentally, the answer you have given makes me that much more interested in this SAML plugin for Moodle.

**Comment by brendanheywood** [comment]
Yeah this plugin was born from the frustration with the other plugins and with the hassle of setting up a whole instance of simplesamlphp for what should instead be a 10 minute task. I hope you find it must easier to use and if you have any issue please keep logging them and I'll help as much as possible :)
