### ISSUE TITLE
Issue with redirect after /login/index.php?saml=off

### ISSUE THREAD

**Issue by caperneoignis** [CatalystIT-AU/moodle-auth_saml2#7]
I have a site running moodle 3.0 on a MariaDB(MySQL) database and am having an issue with the redirect. It looks like it is an absolute path and is stripping away the path from the URL. Example. http://localhost/moodle/login/index.php?saml=off gets me to the login page, but when I put in the correct login, I get redirected to this. http://localhost/simplesaml/module.php/core/postredirect.php?RedirId=[{Long Key Value }] as you can see the /moodle/ gets stripped and causes the server to dead end. Saml2 works fine for dual login and SSO. It's when I try to do the bypass, that everything goes sideways. Any idea what could be causing this?

**Comment by brendanheywood** [comment]
I suspect this is two bugs, 1 is the saml=off logic not working for some people which is already logged. And a second around Moodles installed into subdirectories. I'll take a look

**Comment by caperneoignis** [comment]
I've also notice this on a non subdirectory install. This is our development server with the sub directory. We also tried it on a production server after hours and had the same result. SSO works fine, it's when we try that saml=off that everything goes sideways and we dead end.

**Comment by brendanheywood** [comment]
Yeah I've just done a test auth against testshib.org using a subdirectory moodle and worked fine, so think it is just the the second bug. Still digging

**Comment by caperneoignis** [comment]
Where does the Url get generated after the successful manual login? I saw the calls for the bypass in the setup/autoload, not sure the filename it's not in front of me. I couldn't see where the URL is generated though.

**Comment by caperneoignis** [comment]
OK. Let me know, I'll be happy to test it.

**Comment by brendanheywood** [comment]
Ok this is fixed, quite a few hairy edge cases to cater for, please give it a test

**Comment by caperneoignis** [comment]
Is it the main branch? Or do you have a development branch I should clone from?

**Comment by caperneoignis** [comment]
Success! Let me check if SSO works.

**Comment by caperneoignis** [comment]
Also good!.

**Comment by brendanheywood** [comment]
Cool bananas thanks :)
